app_dashboard:
    path: /
    controller: App\Dashboard\Action\DashboardAction
    methods: GET

app_contractor_list:
    path: /contractors/
    controller: App\Contractor\Action\ListContractorsAction
    methods: GET

app_contractor_add:
    path: /contractors/add
    controller: App\Contractor\Action\AddContractorAction
    methods: [GET, POST]

app_contractor_get:
    path: /contractors/{contractorId}
    controller: App\Contractor\Action\GetContractorAction
    methods: [GET, POST]

app_contractor_delete:
    path: /contractors/delete/{contractorId}
    controller: App\Contractor\Action\DeleteContractorAction
    methods: GET

app_product_list:
    path: /products/
    controller: App\Product\Action\ListProductsAction
    methods: GET

app_product_add:
    path: /products/add
    controller: App\Product\Action\AddProductAction
    methods: [GET, POST]

app_product_get:
    path: /products/{productId}
    controller: App\Product\Action\GetProductAction
    methods: [GET, POST]

app_product_delete:
    path: /products/delete/{productId}
    controller: App\Product\Action\DeleteProductAction
    methods: GET